[package]
name = "love"
version = "0.1.0"
edition = "2024"

[dependencies]
crossterm = { version = "0.29.0", features = ["osc52"] }
ratatui = "0.29.0"
tree-sitter-highlight = "0.25.8"
tree-sitter-rust = "0.24.0"
